package in.com.psi.dashboard.entity;

// Generated 6 Feb, 2016 10:56:52 AM by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * ActionHistory generated by hbm2java
 */
@Entity
@Table(name = "action_history", catalog = "dashboard")
public class ActionHistory implements java.io.Serializable {

	private Long id;
	private String action;
	private String actionPerformedFor;
	private String actionPerformedBy;
	private long timestamp;

	public ActionHistory() {
	}

	public ActionHistory(String action, String actionPerformedFor,
			String actionPerformedBy, long timestamp) {
		this.action = action;
		this.actionPerformedFor = actionPerformedFor;
		this.actionPerformedBy = actionPerformedBy;
		this.timestamp = timestamp;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Column(name = "action", nullable = false)
	public String getAction() {
		return this.action;
	}

	public void setAction(String action) {
		this.action = action;
	}

	@Column(name = "action_performed_for", nullable = false)
	public String getActionPerformedFor() {
		return this.actionPerformedFor;
	}

	public void setActionPerformedFor(String actionPerformedFor) {
		this.actionPerformedFor = actionPerformedFor;
	}

	@Column(name = "action_performed_by", nullable = false)
	public String getActionPerformedBy() {
		return this.actionPerformedBy;
	}

	public void setActionPerformedBy(String actionPerformedBy) {
		this.actionPerformedBy = actionPerformedBy;
	}

	@Column(name = "timestamp", nullable = false)
	public long getTimestamp() {
		return this.timestamp;
	}

	public void setTimestamp(long timestamp) {
		this.timestamp = timestamp;
	}

}
