package in.com.psi.dashboard.entity;

// Generated 21 Jan, 2016 2:25:02 PM by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

// TODO: Auto-generated Javadoc
/**
 * Cities generated by hbm2java.
 */
@Entity
@Table(name = "cities", catalog = "dashboard")
public class Cities implements java.io.Serializable {

	/** The id. */
	private Integer id;
	
	/** The name. */
	private String name;
	
	/** The state id. */
	private int stateId;

	/**
	 * Instantiates a new cities.
	 */
	public Cities() {
	}

	/**
	 * Instantiates a new cities.
	 *
	 * @param name the name
	 * @param stateId the state id
	 */
	public Cities(String name, int stateId) {
		this.name = name;
		this.stateId = stateId;
	}

	/**
	 * Gets the id.
	 *
	 * @return the id
	 */
	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	/**
	 * Sets the id.
	 *
	 * @param id the new id
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * Gets the name.
	 *
	 * @return the name
	 */
	@Column(name = "name", nullable = false, length = 30)
	public String getName() {
		return this.name;
	}

	/**
	 * Sets the name.
	 *
	 * @param name the new name
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * Gets the state id.
	 *
	 * @return the state id
	 */
	@Column(name = "state_id", nullable = false)
	public int getStateId() {
		return this.stateId;
	}

	/**
	 * Sets the state id.
	 *
	 * @param stateId the new state id
	 */
	public void setStateId(int stateId) {
		this.stateId = stateId;
	}

}
