package in.com.psi.dashboard.entity;

// Generated 6 Feb, 2016 10:56:52 AM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * CompanyDetails generated by hbm2java
 */
@Entity
@Table(name = "company_details", catalog = "dashboard")
public class CompanyDetails implements java.io.Serializable {

	private Integer id;
	private String name;
	private String address;
	private String phoneNo;
	private Set<Employee> employees = new HashSet<Employee>(0);

	public CompanyDetails() {
	}

	public CompanyDetails(String name) {
		this.name = name;
	}

	public CompanyDetails(String name, String address, String phoneNo,
			Set<Employee> employees) {
		this.name = name;
		this.address = address;
		this.phoneNo = phoneNo;
		this.employees = employees;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "name", nullable = false)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "address")
	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	@Column(name = "phone_no", length = 20)
	public String getPhoneNo() {
		return this.phoneNo;
	}

	public void setPhoneNo(String phoneNo) {
		this.phoneNo = phoneNo;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "companyDetails")
	public Set<Employee> getEmployees() {
		return this.employees;
	}

	public void setEmployees(Set<Employee> employees) {
		this.employees = employees;
	}

}
