package in.com.psi.dashboard.entity;

// Generated 21 Jan, 2016 2:25:02 PM by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

// TODO: Auto-generated Javadoc
/**
 * Countries generated by hbm2java.
 */
@Entity
@Table(name = "countries", catalog = "dashboard")
public class Countries implements java.io.Serializable {

	/** The id. */
	private Integer id;
	
	/** The sortname. */
	private String sortname;
	
	/** The name. */
	private String name;

	/**
	 * Instantiates a new countries.
	 */
	public Countries() {
	}

	/**
	 * Instantiates a new countries.
	 *
	 * @param sortname the sortname
	 * @param name the name
	 */
	public Countries(String sortname, String name) {
		this.sortname = sortname;
		this.name = name;
	}

	/**
	 * Gets the id.
	 *
	 * @return the id
	 */
	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	/**
	 * Sets the id.
	 *
	 * @param id the new id
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * Gets the sortname.
	 *
	 * @return the sortname
	 */
	@Column(name = "sortname", nullable = false, length = 3)
	public String getSortname() {
		return this.sortname;
	}

	/**
	 * Sets the sortname.
	 *
	 * @param sortname the new sortname
	 */
	public void setSortname(String sortname) {
		this.sortname = sortname;
	}

	/**
	 * Gets the name.
	 *
	 * @return the name
	 */
	@Column(name = "name", nullable = false, length = 150)
	public String getName() {
		return this.name;
	}

	/**
	 * Sets the name.
	 *
	 * @param name the new name
	 */
	public void setName(String name) {
		this.name = name;
	}

}
