package in.com.psi.dashboard.entity;

// Generated 6 Feb, 2016 10:56:52 AM by Hibernate Tools 4.3.1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * DesignationHistory generated by hbm2java
 */
@Entity
@Table(name = "designation_history", catalog = "dashboard")
public class DesignationHistory implements java.io.Serializable {

	private Integer id;
	private Employee employee;
	private String oldDesignation;
	private String newDesignation;
	private Date dateOfDesignationChange;

	public DesignationHistory() {
	}

	public DesignationHistory(Employee employee, String oldDesignation,
			String newDesignation, Date dateOfDesignationChange) {
		this.employee = employee;
		this.oldDesignation = oldDesignation;
		this.newDesignation = newDesignation;
		this.dateOfDesignationChange = dateOfDesignationChange;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "employee_id")
	public Employee getEmployee() {
		return this.employee;
	}

	public void setEmployee(Employee employee) {
		this.employee = employee;
	}

	@Column(name = "old_designation")
	public String getOldDesignation() {
		return this.oldDesignation;
	}

	public void setOldDesignation(String oldDesignation) {
		this.oldDesignation = oldDesignation;
	}

	@Column(name = "new_designation")
	public String getNewDesignation() {
		return this.newDesignation;
	}

	public void setNewDesignation(String newDesignation) {
		this.newDesignation = newDesignation;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "date_of_designation_change", length = 19)
	public Date getDateOfDesignationChange() {
		return this.dateOfDesignationChange;
	}

	public void setDateOfDesignationChange(Date dateOfDesignationChange) {
		this.dateOfDesignationChange = dateOfDesignationChange;
	}

}
