package in.com.psi.dashboard.entity;

// Generated 6 Feb, 2016 10:56:52 AM by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * OtherUser generated by hbm2java
 */
@Entity
@Table(name = "other_user", catalog = "dashboard")
public class OtherUser implements java.io.Serializable {

	private Integer id;
	private String hostIp;
	private Boolean status;
	private String hostUsername;
	private String hostPassword;

	public OtherUser() {
	}

	public OtherUser(String hostIp, Boolean status, String hostUsername,
			String hostPassword) {
		this.hostIp = hostIp;
		this.status = status;
		this.hostUsername = hostUsername;
		this.hostPassword = hostPassword;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "host_ip", length = 30)
	public String getHostIp() {
		return this.hostIp;
	}

	public void setHostIp(String hostIp) {
		this.hostIp = hostIp;
	}

	@Column(name = "status")
	public Boolean getStatus() {
		return this.status;
	}

	public void setStatus(Boolean status) {
		this.status = status;
	}

	@Column(name = "host_username", length = 50)
	public String getHostUsername() {
		return this.hostUsername;
	}

	public void setHostUsername(String hostUsername) {
		this.hostUsername = hostUsername;
	}

	@Column(name = "host_password", length = 50)
	public String getHostPassword() {
		return this.hostPassword;
	}

	public void setHostPassword(String hostPassword) {
		this.hostPassword = hostPassword;
	}

}
