package in.com.psi.dashboard.entity;

// Generated 6 Feb, 2016 10:56:52 AM by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * ProfessionalDetails generated by hbm2java
 */
@Entity
@Table(name = "professional_details", catalog = "dashboard")
public class ProfessionalDetails implements java.io.Serializable {

	private Long id;
	private Employee employee;
	private String skillSet;
	private String qualifications;
	private String certifications;

	public ProfessionalDetails() {
	}

	public ProfessionalDetails(Employee employee, String skillSet,
			String qualifications, String certifications) {
		this.employee = employee;
		this.skillSet = skillSet;
		this.qualifications = qualifications;
		this.certifications = certifications;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "employee_id")
	public Employee getEmployee() {
		return this.employee;
	}

	public void setEmployee(Employee employee) {
		this.employee = employee;
	}

	@Column(name = "skill_set", length = 2000)
	public String getSkillSet() {
		return this.skillSet;
	}

	public void setSkillSet(String skillSet) {
		this.skillSet = skillSet;
	}

	@Column(name = "qualifications", length = 2000)
	public String getQualifications() {
		return this.qualifications;
	}

	public void setQualifications(String qualifications) {
		this.qualifications = qualifications;
	}

	@Column(name = "certifications", length = 2000)
	public String getCertifications() {
		return this.certifications;
	}

	public void setCertifications(String certifications) {
		this.certifications = certifications;
	}

}
