package in.com.psi.dashboard.entity;

// Generated 21 Jan, 2016 2:25:02 PM by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

// TODO: Auto-generated Javadoc
/**
 * States generated by hbm2java.
 */
@Entity
@Table(name = "states", catalog = "dashboard")
public class States implements java.io.Serializable {

	/** The id. */
	private Integer id;
	
	/** The name. */
	private String name;
	
	/** The country id. */
	private int countryId;

	/**
	 * Instantiates a new states.
	 */
	public States() {
	}

	/**
	 * Instantiates a new states.
	 *
	 * @param name the name
	 * @param countryId the country id
	 */
	public States(String name, int countryId) {
		this.name = name;
		this.countryId = countryId;
	}

	/**
	 * Gets the id.
	 *
	 * @return the id
	 */
	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	/**
	 * Sets the id.
	 *
	 * @param id the new id
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * Gets the name.
	 *
	 * @return the name
	 */
	@Column(name = "name", nullable = false, length = 30)
	public String getName() {
		return this.name;
	}

	/**
	 * Sets the name.
	 *
	 * @param name the new name
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * Gets the country id.
	 *
	 * @return the country id
	 */
	@Column(name = "country_id", nullable = false)
	public int getCountryId() {
		return this.countryId;
	}

	/**
	 * Sets the country id.
	 *
	 * @param countryId the new country id
	 */
	public void setCountryId(int countryId) {
		this.countryId = countryId;
	}

}
